package gormgen

import "text/template"

// Make sure that the template compiles during package initialization
func parseTemplateOrPanic(t string) *template.Template {
	tpl, err := template.New("output_template").Parse(t)
	if err != nil {
		panic(err)
	}
	return tpl
}

var outputTemplate = parseTemplateOrPanic(`
package {{.PkgName}}

///////////////////////////////////////////////////////////
// THIS FILE IS AUTO GENERATED by gormgen, DON'T EDIT IT //
//        ANY CHANGES DONE HERE WILL BE LOST             //
///////////////////////////////////////////////////////////

import "github.com/siskinc/gormgen"
import "github.com/jinzhu/gorm"
import "fmt"

{{range .Structs}}

	func (t *{{.StructName}}) Save() error {
		return {{$.Client}}.Save(t).Error
	}

	func (t *{{.StructName}}) Delete() error {
		return {{$.Client}}.Delete(t).Error
	}

	type {{.QueryBuilderName}} struct {
		order []string
		where []struct{
			prefix string
			value interface{}
		}
		limit int
		offset int
	}

	func (qb *{{.QueryBuilderName}}) buildQuery() *gorm.DB {
		ret := {{$.Client}}
		for _, where := range qb.where {
			ret = ret.Where(where.prefix, where.value)
		}
		for _, order := range qb.order {
			ret = ret.Order(order)
		}
		ret = ret.Limit(qb.limit).Offset(qb.offset)
		return ret
	}

	func (qb *{{.QueryBuilderName}}) Count() (int, error) {
		var c int
		res := qb.buildQuery().Model(&{{.StructName}}{}).Count(&c)
		if res.RecordNotFound() {
			c = 0
		}
		return c, res.Error
	}

	func (qb *{{.QueryBuilderName}}) First() (*{{.StructName}}, error) {
		ret := &{{.StructName}}{}
		res := qb.buildQuery().First(ret)
		if res.RecordNotFound() {
			ret = nil
		}
		return ret, res.Error
	}

	func (qb *{{.QueryBuilderName}}) QueryOne() (*{{.StructName}}, error) {
		qb.limit = 1
		ret, err := qb.QueryAll()
		if len(ret) > 0 {
			return &ret[0], err
		}
		return nil, err
	}

	func (qb *{{.QueryBuilderName}}) QueryAll() ([]{{.StructName}}, error) {
		ret := []{{.StructName}}{}
		err := qb.buildQuery().Find(&ret).Error
		return ret, err
	}

	func (qb *{{.QueryBuilderName}}) Limit(limit int) *{{.QueryBuilderName}} {
		qb.limit = limit
		return qb
	}

	func (qb *{{.QueryBuilderName}}) Offset(offset int) *{{.QueryBuilderName}} {
		qb.offset = offset
		return qb
	}

	{{$queryBuilderName := .QueryBuilderName}}
	{{range .Fields}}
		func (qb *{{$queryBuilderName}}) Where{{call $.Helpers.Titelize .FieldName}}(p {{if ne ($.PkgName) "gormgen"}}gormgen.{{end}}Predicate, value {{.FieldType}}) *{{$queryBuilderName}} {
			 qb.where = append(qb.where, struct {
				prefix string
				value interface{}
			}{
				fmt.Sprintf("%v %v ?", "{{.ColumnName}}", p),
				value,
			})
			return qb
		}

		func (qb *{{$queryBuilderName}}) OrderBy{{call $.Helpers.Titelize .FieldName}}(asc bool) *{{$queryBuilderName}} {
			order := "DESC"
			if asc {
				order = "ASC"
			}

			qb.order = append(qb.order, "{{.ColumnName}} " + order)
			return qb
		}
	{{end}}
{{end}}
`)
